spring:
  application:
    name: rest-api-local
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: item
      username: item
      password: item

logging.level:
  elliot.restapi: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  org.springframework.data.mongodb.repository: DEBUG

server:
  port: ${PORT:8001}
