spring:
  application:
    name: rest-api-local
    version: 0.0.1
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatbot
      username: chatbot
      password: chatbot

logging.level:
  elliot.restapi: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  org.springframework.data.mongodb.repository: DEBUG



server:
  port: ${PORT:8001}
